### ISSUE TITLE
Ksc not part of kerbNet 

### ISSUE THREAD

**Issue by TenchuHawke** [Galileo88/Galileos-Planet-Pack#19] opened 2017-10-19 21:08 UTC
I installed opm, gpp, and the mod so gpp is put outside the standard system (gpp extended?). Kerbal has no ksc on kerbNet, though there is a gsc. Theorizing that the kerbal relays didn't get moved.

**Comment by Galileo88** [comment] 2017-10-19 21:39
Ill take a look. I think i know what the issue is.

**Comment by TenchuHawke** [comment] 2017-10-27 16:11
Looks like all the launch locations are wrong.  One is in midair, one is underwater.  I suspect they are from Gael.  I accidentally switched from the KSP (Which doesn't have a launch pad icon) and can't switch back.  Any progress?

**Comment by Galileo88** [comment] 2017-11-30 08:13
Everything should be fixed with the latest update.

**Closed by Galileo88** 2017-11-30 08:13 UTC
